name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.11.2'
      - run: mix deps.get
      - run: mix test --exclude too_slow